### ISSUE TITLE
The Hub

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-hub#1]
## What

Create the basic SignalR app. Will have the ability to connect a client, create a session for the single client, send a "Ping" and receive a "Pong", and dispose of connection when client disconnects.

## Todo

- [x] Create solution
- [x] Create web app project
- [x] Create xunit project
- [x] Add SignalR and endpoint
- [x] Action for PR verify
- [x] Action to deploy to Cloud Run on merge to main
- [x] Code analyzer on PR
- [x] Disable concurrency
- [x] Issue templates
- [x] License
- [x] README
- GameHub
  - [x] Create session with group and add client
  - [x] update player account with session details
  - [x] On connect send session update
  - [x] Find and use existing session is exists
  - [x] On disconnect dispose connection and group
